### ISSUE TITLE
TypeError: Cannot read property 'querySelector' of null - Outdated sweetAlert?

### ISSUE THREAD

**Issue by mduqueoviedo** [lipis/bootstrap-sweetalert#38]
I get this error `TypeError: Cannot read property 'querySelector' of null` when running the plugin. I found it was a bug in the original SweetAlert and that it was already solved. Is there any chance your improved version is not up to date?

**Comment by lipis** [comment]
it very much a chance actually.. I haven't update it this project for a while and if there is anyone that could actually make a PR with the latest parent project would be nice!

**Comment by abitdodgy** [comment]
I'm running into the same issue. @lipis what do you mean update the parent object? I tried replacing the JS source files, but that didn't work. I think it's a bit more complicated than that. If you care to elaborate a little I might give it a crack.

**Comment by lipis** [comment]
This has to happen.. https://github.com/lipis/bootstrap-sweetalert/compare/master...t4t5:master

**Comment by alekitto** [comment]
There are chances this has been resolved now. @mduqueoviedo can you check if this is still an issue?

**Comment by Krystus** [comment]
`TypeError: null is not an object (evaluating 'i.querySelector')`

Still no fix?

**Comment by alekitto** [comment]
This version of sweetalert has been sync'd to the original one.
Have you tried the master branch version?

**Comment by lipis** [comment]
Let's verify it and if it's fixed.. burn it @alekitto :)

**Comment by Krystus** [comment]
@alekitto works like a charm. Now I see that npm version is not installed after download. No dist folder etc. Strage thing that I need to import that js in browerify with full path 'var sweetalert = require('../../../node_modules/bootstrap-sweetalert/dist/sweetalert.min.js');' because name 'bootstrap-sweetalert' give me "not found" error.

`Error: ENOTDIR: not a directory, stat '/Applications/Atom.app/Contents/Resources/app.asar/exports/bootstrap-sweetalert'
    at Error (native)`

**Comment by alekitto** [comment]
Ok, probably we just need to tag a new release.
Closing this and continuing in #56
