### ISSUE TITLE
Can you update the sweetalert version?

### ISSUE THREAD

**Issue by ycs77** [lipis/bootstrap-sweetalert#81]
Now Sweetalert version is to version 2.

https://github.com/t4t5/sweetalert/releases

**Comment by belgarad** [comment]
+

**Comment by lipis** [comment]
I'm happy to accept a PR.. but I really don't have time for merging this thing :( I'm sorry

**Comment by imgrammy** [comment]
@lipis would you please tell some about how to draw it out for bootstrap from the original version? Someone might try to do it.

**Comment by lipis** [comment]
It's been like a million years ago.. :) But if I remember correctly.. pretty straight forward..

**Comment by crustamet** [comment]
Please update this to bootstrap 4 pls...

**Comment by lipis** [comment]
I'm not longer maintaining this.. if anyone is up for doing it let me know..

**Comment by alekitto** [comment]
Sweetalert has been completely rewritten in typescript, could not be easy to upgrade to a new version. I could try to replicate the modifications in the next weeks.

**Comment by lipis** [comment]
Feel free.. I can add you as a moderator

**Comment by jefersonfs** [comment]
Hello!
SweetAlert 2 have suport to button class..
Look my test : https://code.sololearn.com/WfbbgUMRT961/#html

**Comment by jrichview** [comment]
My understanding is that "SweetAlert 2" (the TypeScript version) is a fork of the original SweetAlert just as this is.  Since it was forked, the original SweetAlert has been updated and is now version 2.X which is obviously very confusing. SweetAlert 2.x vs SweetAlert 2 (v-whatever?).

So updating to the most recent "SweetAlert (2.x)" would probably make more sense than updating to SweetAlert 2, wouldn't it?
